### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by AngryMaciek** [AngryMaciek/angry-moran-simulator#18]
Move the docs into _GH Pages_ or _ReadTheDocs_, change `md` to `rst`; use _sphinx_; add CI and README shield, add proper code comments.

**Comment by AngryMaciek** [comment]
After the documentation is built and we have an URL: add a link to PyPI and conda pages.

**Comment by AngryMaciek** [comment]
This might be a good place to start:
https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/

**Comment by AngryMaciek** [comment]
* remember to writeup math background in the docs
* also: add links to better explanations, yt videos?

**Comment by AngryMaciek** [comment]
read:
- [x] https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html
- [x] https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/#id1
- [x] https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
- [x] https://matplotlib.org/sampledoc/
- [x] https://docs.python-guide.org/writing/style/#code-style
- [x] https://realpython.com/documenting-python-code/
- [x] https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/
- [x] https://techwritingmatters.com/documenting-with-sphinx-tutorial-intro-overview
- [x] https://www.sphinx-doc.org/en/master/usage/quickstart.html

**Comment by AngryMaciek** [comment]
// blocked by #17 and #19

**Comment by AngryMaciek** [comment]
TASK LIST
========

- [ ] setup sphinx locally
- [ ] setup GitHub Action with docs build and auto-push
- [ ] populate the sphinx docs with all the info about the package
- [ ] create docs section with API

**Comment by AngryMaciek** [comment]
# TODO

- [x] toctrees styling: https://github.com/readthedocs/sphinx_rtd_theme/issues/1112#issue-849974866
- [x] clean URLs?
- [x] Changelog markdown parsing & include with toc subsections
- [x] add main picture to the mainpage: https://stackoverflow.com/questions/66969914/sphinx-documentation-custom-images-dir-and-static-directory-for-html-docs
- [x] wrap license text: https://stackoverflow.com/questions/66971299/sphinx-documentation-with-readthedocs-theme-text-block-wrapping | https://github.com/sphinx-doc/sphinx/issues/9090
- [x] example results section
- [x] search page (removed): https://github.com/readthedocs/sphinx_rtd_theme/issues/998
- [x] bg section
- [x] add old docs
- [x] create docs section with API
- [x] Module index section - not found? https://stackoverflow.com/questions/13838368/no-generation-of-the-module-index-modindex-when-using-sphinx Solution described here: https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/

**Comment by AngryMaciek** [comment]
* Finish this issue with `1.0.39`, publish new version to Zenodo too? clean the CHANGELOG! Update project's homepage in other resources too!
* binder: pkg version update!
* clean gh pages branch!

**Comment by AngryMaciek** [comment]
* binder: pkg version update!
